spring:
  datasource:
    url: @dataSource.url@
    username: @dataSource.user@
    password: @dataSource.password@
    tomcat:
      max-active: 4
      max-idle: 2
      max-wait: 10000
      remove-abandoned: true
      log-abandoned: true
      validation-query: SELECT 1
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

project:
  jwtSession:
    expirationInMinutes: 1440   # Minutos en 1 d√≠a
    signKey: Bu:GW8bgPlEw