spring:
  datasource:
    url: @dataSource.url@
    username: @dataSource.user@
    password: @dataSource.password@
    tomcat:
      max-active: 4
      max-idle: 2
      max-wait: 5000
      remove-abandoned: true
      log-abandoned: true
      validation-query: SELECT 1
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 16MB



project:
  jwtSession:
    expirationInMinutes: 720   # Minutos en 12 horas
    signKey: Bu:GW8bgPlEw
